name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "${{ DEPLOY_SIGNING_KEY }}" | base64 --decode > keystore.jks
          echo "${{ DEPLOY_SIGNING_PROPERTIES }}" | base64 --decode > keystore.properties
          echo "${{ GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bundleRelease

      - uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: |
            app/**/*.aab
            app/**/mapping.txt

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "${{ secrets.DEPLOY_SIGNING_KEY }}" | base64 --decode > keystore.jks
          echo "${{ secrets.DEPLOY_SIGNING_PROPERTIES }}" | base64 --decode > keystore.properties
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: assembleRelease

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: |
            app/**/*.apk

  publish-aab:
    runs-on: ubuntu-latest
    needs: [ build-aab ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: release-bundle

      - run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > service-account.json

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: wiki.depasquale.cursola
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: completed
          inAppUpdatePriority: 3
          mappingFile: app/build/outputs/mapping/release/mapping.txt

  publish-apk:
    runs-on: ubuntu-latest
    needs: [ build-apk ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: release-apk

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
